services:
  api:
    image: "pdv:latest"
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/pdv
      DATABASE_USER: caio
      DATABASE_PASSWORD: 123
      SPRING_ACTIVE_PROFILE: prod
    networks:
      - pdv-net
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: pdv
      POSTGRES_USER: caio
      POSTGRES_PASSWORD: 123
    networks:
      - pdv-net
    volumes:
      - "pdv-data:/var/lib/postgresql/data"

networks:
  pdv-net:
    driver: bridge

volumes:
  pdv-data: